In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,r2_score



from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r"D:\shrajith\D_S PROJECT\capstone\Life Expectancy Data.csv")

In [3]:
pd.set_option('display.max_columns',None)
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [4]:
df.head(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279.0,74,0.01,79.679367,66.0,1989,16.7,102,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281.0,77,0.01,56.762217,63.0,2861,16.2,106,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287.0,80,0.03,25.873925,64.0,1599,15.7,110,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295.0,82,0.02,10.910156,63.0,1141,15.2,113,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4
9,Afghanistan,2006,Developing,57.3,295.0,84,0.03,17.171518,64.0,1990,14.7,116,58.0,7.43,58.0,0.1,272.563770,2589345.0,19.2,19.3,0.405,8.1

In [5]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [8]:
df.columns = df.columns.str.strip()

In [9]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles', 'BMI', 'under-five deaths', 'Polio', 'Total expenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness  1-19 years',
       'thinness 5-9 years', 'Income composition of resources', 'Schooling'],
      dtype='object')

In [10]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
BMI                                 34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
HIV/AIDS                             0
GDP                                448
Population                         652
thinness  1-19 years                34
thinness 5-9 years                  34
Income composition of resources    167
Schooling                          163
dtype: int64

In [11]:
df=df.dropna(subset = ['Life expectancy','Adult Mortality','BMI','Polio',
                            'Diphtheria','thinness  1-19 years','thinness 5-9 years'])
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            175
percentage expenditure               0
Hepatitis B                        525
Measles                              0
BMI                                  0
under-five deaths                    0
Polio                                0
Total expenditure                  212
Diphtheria                           0
HIV/AIDS                             0
GDP                                435
Population                         644
thinness  1-19 years                 0
thinness 5-9 years                   0
Income composition of resources    160
Schooling                          160
dtype: int64

In [12]:
grouped_mean = df.groupby('Country')['Alcohol'].transform('mean')
df['Alcohol']=df['Alcohol'].fillna(grouped_mean)


df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                              0
percentage expenditure               0
Hepatitis B                        525
Measles                              0
BMI                                  0
under-five deaths                    0
Polio                                0
Total expenditure                  212
Diphtheria                           0
HIV/AIDS                             0
GDP                                435
Population                         644
thinness  1-19 years                 0
thinness 5-9 years                   0
Income composition of resources    160
Schooling                          160
dtype: int64

In [13]:
df['Hepatitis B'] = df['Hepatitis B'].fillna(df['Hepatitis B'].median())
print(df['Hepatitis B'].isnull().sum())
df['Hepatitis B'].head(10)

0

0    65.0
1    62.0
2    64.0
3    67.0
4    68.0
5    66.0
6    63.0
7    64.0
8    63.0
9    64.0
Name: Hepatitis B, dtype: float64

In [14]:
grouped_median = df.groupby('Country')[['Total expenditure','GDP','Population',
                            'Income composition of resources','Schooling']].transform('median')

df[['Total expenditure','GDP','Population',
    'Income composition of resources','Schooling']]=df[['Total expenditure','GDP','Population',
                                                        'Income composition of resources','Schooling']].fillna(grouped_median)


print(df[['Total expenditure','GDP','Population',
                'Income composition of resources','Schooling']].isnull().sum())

Total expenditure                   32
GDP                                400
Population                         640
Income composition of resources    160
Schooling                          160
dtype: int64

In [15]:
median = df[['Total expenditure','GDP','Population',
                'Income composition of resources','Schooling']].median()

df[['Total expenditure','GDP','Population',
    'Income composition of resources','Schooling']] = df[['Total expenditure','GDP','Population',
                                                        'Income composition of resources','Schooling']].fillna(median)
(df[['Total expenditure','GDP','Population',
                'Income composition of resources','Schooling']].isnull().sum())

Total expenditure                  0
GDP                                0
Population                         0
Income composition of resources    0
Schooling                          0
dtype: int64

In [16]:
print(df.isnull().sum())

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
BMI                                0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
HIV/AIDS                           0
GDP                                0
Population                         0
thinness  1-19 years               0
thinness 5-9 years                 0
Income composition of resources    0
Schooling                          0
dtype: int64

In [17]:
df.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
BMI                                float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
HIV/AIDS                           float64
GDP                                float64
Population                         float64
thinness  1-19 years               float64
thinness 5-9 years                 float64
Income composition of resources    float64
Schooling                          float64
dtype: object

In [18]:
df['Status'].unique()

array(['Developing', 'Developed'], dtype=object)

In [19]:
# Define valid ranges
valid_ranges = {
    'BMI': (15, 40),
    'Measles': (0, 1000),
    'infant deaths': (0, 1000),
    'under-five deaths': (0, 1000)
}

# Loop through each column
for col in valid_ranges:
    
    # Get min and max values for that column
    min_val = valid_ranges[col][0]
    max_val = valid_ranges[col][1]
    
    # Loop through each value in the column
    new_values = []
    
    for value in df[col]:
        
        if value < min_val:
            new_values.append(min_val)
        
        elif value > max_val:
            new_values.append(max_val)
        
        else:
            new_values.append(value)
    
    # Replace column with cleaned values
    df[col] = new_values

# Show summary
print(df[['BMI', 'Measles', 'infant deaths', 'under-five deaths']].describe())

               BMI      Measles  infant deaths  under-five deaths
count  2888.000000  2888.000000    2888.000000        2888.000000
mean     31.218560   250.605263      28.237188          37.484418
std      10.463624   387.131315      94.239557         113.452082
min      15.000000     0.000000       0.000000           0.000000
25%      19.300000     0.000000       0.000000           0.000000
50%      40.000000    17.000000       3.000000           4.000000
75%      40.000000   352.250000      21.000000          26.000000
max      40.000000  1000.000000    1000.000000        1000.000000

In [20]:
# Selecting only numeric columns
numeric_columns = df.select_dtypes(include=['float64', 'int64'])

# Geting correlation values with Life expectancy
life_corr = numeric_columns.corr()['Life expectancy']

In [21]:
print(life_corr)

Year                               0.170772
Life expectancy                    1.000000
Adult Mortality                   -0.693189
infant deaths                     -0.236794
Alcohol                            0.407194
percentage expenditure             0.381173
Hepatitis B                        0.175716
Measles                           -0.336887
BMI                                0.555725
under-five deaths                 -0.297828
Polio                              0.464166
Total expenditure                  0.216967
Diphtheria                         0.478194
HIV/AIDS                          -0.560382
GDP                                0.431327
Population                        -0.029598
thinness  1-19 years              -0.476342
thinness 5-9 years                -0.470744
Income composition of resources    0.689069
Schooling                          0.724434
Name: Life expectancy, dtype: float64

In [22]:
df.to_csv("CAPSTONE_Life_Expectancy_CLEANED.csv", index=False)

# Encoding

In [23]:
le=LabelEncoder()
df['Status']=le.fit_transform(df['Status'])
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,1,65.0,263.0,62,0.01,71.279624,65.0,1000,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,1,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,1,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,1,59.5,272.0,69,0.01,78.184215,67.0,1000,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,1,59.2,275.0,71,0.01,7.097109,68.0,1000,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

# ML

In [24]:
# Remove unwanted columns
df = df.drop(['Year', 'Measles', 'Population', 'Country'], axis=1)

In [25]:
df.head()

,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,1,65.0,263.0,62,0.01,71.279624,65.0,19.1,83,6.0,8.16,65.0,0.1,584.259210,17.2,17.3,0.479,10.1
1,1,59.9,271.0,64,0.01,73.523582,62.0,18.6,86,58.0,8.18,62.0,0.1,612.696514,17.5,17.5,0.476,10.0
2,1,59.9,268.0,66,0.01,73.219243,64.0,18.1,89,62.0,8.13,64.0,0.1,631.744976,17.7,17.7,0.470,9.9
3,1,59.5,272.0,69,0.01,78.184215,67.0,17.6,93,67.0,8.52,67.0,0.1,669.959000,17.9,18.0,0.463,9.8
4,1,59.2,275.0,71,0.01,7.097109,68.0,17.2,97,68.0,7.87,68.0,0.1,63.537231,18.2,18.2,0.454,9.5

In [26]:
# feature selection
x = df.drop('Life expectancy',axis=1)
y = df['Life expectancy']

# LinearRegression

In [27]:
# train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(y_test.shape)

# Model training
lr=LinearRegression()
lr.fit(x_train,y_train)

# prediction
y_pred=lr.predict(x_test)
y_pred

# evaluate
r2 = r2_score(y_test,y_pred)
print("LinearRegression:",r2)

(2310, 17)
(578,)
LinearRegression: 0.8217579681437389

# RandomForestRegressor

In [28]:
# train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_test.shape)

# Model training
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(x_train, y_train)

# prediction
y_pred = rf.predict(x_test)

# evaluate
r2 = r2_score(y_test, y_pred)
print("Random Forest R2:", r2)

(2310, 17)
(578,)
Random Forest R2: 0.9574869279225398

# DecisionTreeRegressor

In [29]:
# train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_test.shape)

# Model training
dt = DecisionTreeRegressor(random_state=42)
dt.fit(x_train, y_train)

# prediction
y_pred = dt.predict(x_test)


# evaluate
r2 = r2_score(y_test, y_pred)
print("Decision Tree R2:", r2)

(2310, 17)
(578,)
Decision Tree R2: 0.9123856057314655

# SVR

In [30]:
# train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_test.shape)

# Scaling 
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Model training
svr = SVR(kernel='rbf')
svr.fit(x_train_scaled, y_train)

# prediction
y_pred = svr.predict(x_test_scaled)

# evaluate
r2 = r2_score(y_test, y_pred)
print("Scaled SVR R2:", r2)

(2310, 17)
(578,)
Scaled SVR R2: 0.8706326460366963

# KNN Regressor

In [31]:
# train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_test.shape)

# Scaling 
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Model training
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(x_train_scaled, y_train)

# prediction
y_pred = knn.predict(x_test_scaled)

# evaluate
r2 = r2_score(y_test, y_pred)
print("KNN Regressor R2:", r2)

(2310, 17)
(578,)
KNN Regressor R2: 0.9052273502201071